import {useEffect,useRef,useState} from "react";
import {createRoot} from "react-dom/client";
import {getHealth,previewDataset,runPreprocessing,selectTarget,uploadDataset} from "./services/api";
import type {DatasetPreview,DatasetSummary} from "./types/dataset";
import type {HealthStatus} from "./types/health";
import type {PreprocessingConfig,PreprocessingRun} from "./types/preprocessing";
const stages=["Upload dataset","Prepare data","Select features","Reduce dimensions","Train models","Compare","Explain","Predict"];
const defaults:Omit<PreprocessingConfig,"dataset_id">={test_size:.2,random_seed:42,duplicate_mode:"remove",numerical_missing:"median",categorical_missing:"most_frequent",categorical_encoding:"one_hot",scaling:"standard",outlier_method:null,outlier_mode:"keep",outlier_threshold:1.5,resampling_method:"none",smote_k_neighbors:5};
function App(){
 const [health,setHealth]=useState<HealthStatus|null>(null),[file,setFile]=useState<File|null>(null),[dataset,setDataset]=useState<DatasetSummary|null>(null),[preview,setPreview]=useState<DatasetPreview|null>(null),[config,setConfig]=useState(defaults),[run,setRun]=useState<PreprocessingRun|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState<string|null>(null);const input=useRef<HTMLInputElement|null>(null);
 useEffect(()=>{getHealth().then(setHealth).catch(()=>setHealth(null))},[]);
 async function upload(){if(!file)return;setBusy(true);setMessage(null);try{const value=await uploadDataset(file);setDataset(value);setPreview(await previewDataset(value.id));setRun(null)}catch(e){setMessage(e instanceof Error?e.message:"Upload failed")}finally{setBusy(false)}}
 async function target(value:string){if(!dataset)return;setBusy(true);try{setDataset(await selectTarget(dataset.id,value));setRun(null)}catch(e){setMessage(e instanceof Error?e.message:"Target failed")}finally{setBusy(false)}}
 async function execute(){if(!dataset?.target_column)return;setBusy(true);setMessage(null);try{setRun(await runPreprocessing({...config,dataset_id:dataset.id}))}catch(e){setMessage(e instanceof Error?e.message:"Preprocessing failed")}finally{setBusy(false)}}
 const columns=dataset?[...dataset.numeric_columns,...dataset.categorical_columns,...dataset.datetime_columns]:[];
 return <div className="app"><header className="topbar"><div className="brand"><div className="mark">Ξ</div><div><strong>EntangleX</strong><span>Q-Health</span></div></div><div className={`status ${health?.status==="ok"?"ok":""}`}><span/>{health?`Platform ${health.status}`:"Backend offline"}</div></header><main>
 <section className="hero compact"><div className="eyebrow">PHASE 4 • TRAINING-ONLY CLASS BALANCING</div><h1>Balance training data without altering the test set.</h1><p>Choose no resampling, Random oversampling, random undersampling, or SMOTE. EntangleX applies balancing only to transformed training data and preserves the held-out test distribution.</p></section>
 <section className="workspace"><div className="uploadCard"><div className="panelHead"><div><div className="eyebrow">DATASET</div><h2>Upload and inspect</h2></div><span className="tag">CSV / XLSX • 25 MB</span></div><input ref={input} hidden type="file" accept=".csv,.xlsx" onChange={(e:{target:HTMLInputElement})=>setFile(e.target.files?.[0]??null)}/><button className="drop" onClick={()=>input.current?.click()}><b>{file?.name??"Choose CSV or XLSX"}</b><span>Files are validated before storage</span></button><div className="actions"><button disabled={!file||busy} onClick={upload}>{busy?"Working…":"Upload dataset"}</button></div>{message&&<div className="error">{message}</div>}</div></section>
 {dataset&&<section className="result"><div className="resultHead"><div><div className="eyebrow">DATASET REGISTERED</div><h2>{dataset.name}</h2><p>{dataset.rows} rows • {dataset.columns} columns</p></div><label>Binary target<select value={dataset.target_column??""} onChange={(e:{target:HTMLSelectElement})=>target(e.target.value)}><option value="">Select target</option>{columns.map(c=><option key={c}>{c}</option>)}</select></label></div><div className="metrics"><Metric label="Samples" value={dataset.rows}/><Metric label="Features" value={dataset.columns}/><Metric label="Missing" value={dataset.total_missing_values}/><Metric label="Duplicates" value={dataset.duplicate_rows}/></div>{preview&&<div className="tableWrap"><table><thead><tr>{preview.columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{preview.rows.slice(0,5).map((row,i)=><tr key={i}>{preview.columns.map(c=><td key={c}>{row[c]===null?"—":String(row[c])}</td>)}</tr>)}</tbody></table></div>}</section>}
 {dataset?.target_column&&<section className="preprocess"><div className="panelHead"><div><div className="eyebrow">PIPELINE CONFIGURATION</div><h2>Training-fitted transformations and balancing</h2></div><span className="tag safe">Split before fit</span></div><div className="configGrid"><Select label="Class balancing" value={config.resampling_method} options={[["none","None"],["random_over","Random oversampling"],["random_under","Random undersampling"],["smote","SMOTE"]]} change={v=>setConfig({...config,resampling_method:v as PreprocessingConfig["resampling_method"]})}/><label>SMOTE neighbors<input type="number" min="1" max="20" disabled={config.resampling_method!=="smote"} value={config.smote_k_neighbors} onChange={(e:{target:HTMLInputElement})=>setConfig({...config,smote_k_neighbors:Number(e.target.value)})}/></label><Select label="Missing numerical" value={config.numerical_missing} options={[["median","Median"],["mean","Mean"]]} change={v=>setConfig({...config,numerical_missing:v as "median"|"mean"})}/><Select label="Encoding" value={config.categorical_encoding} options={[["one_hot","One-hot"],["ordinal","Ordinal"]]} change={v=>setConfig({...config,categorical_encoding:v as "one_hot"|"ordinal"})}/><Select label="Scaling" value={config.scaling} options={[["standard","StandardScaler"],["minmax","MinMaxScaler"]]} change={v=>setConfig({...config,scaling:v as "standard"|"minmax"})}/><label>Test size<input type="number" min=".1" max=".4" step=".05" value={config.test_size} onChange={(e:{target:HTMLInputElement})=>setConfig({...config,test_size:Number(e.target.value)})}/></label></div><div className="fitRule"><b>Leakage control</b><span>Stratified split → fit transformations on train only → resample transformed training rows only → preserve held-out test.</span></div><button disabled={busy} onClick={execute}>{busy?"Running…":"Run preprocessing"}</button></section>}
 {run&&<section className="runResult"><div className="eyebrow">RUN COMPLETED</div><h2>Training distribution recorded</h2><div className="metrics"><Metric label="Train after balancing" value={run.train_rows_after_resampling}/><Metric label="Test rows untouched" value={run.test_rows}/><Metric label="Rows added" value={run.resampling_rows_added}/><Metric label="Rows removed" value={run.resampling_rows_removed}/></div><div className="split"><span>{JSON.stringify(run.train_class_distribution_before_resampling)}</span><b>→</b><span>{run.resampling_method}: {JSON.stringify(run.train_class_distribution_after_resampling)}</span></div></section>}
 <section className="panel"><div className="panelHead"><div><div className="eyebrow">RESEARCH WORKFLOW</div><h2>One defensible path from data to evidence</h2></div></div><div className="flow">{stages.map((s,i)=><div className={`step ${i<2?"active":""}`} key={s}><span>{String(i+1).padStart(2,"0")}</span><b>{s}</b></div>)}</div></section><section className="notice"><b>Research use only.</b> Predictions are not a substitute for professional medical diagnosis or clinical validation.</section></main><footer>EntangleX Q-Health • Training-only fitting • No assumed quantum advantage</footer></div>
}
function Metric({label,value}:{label:string;value:string|number}){return <div><span>{label}</span><b>{value}</b></div>}
function Select({label,value,options,change}:{label:string;value:string;options:string[][];change:(v:string)=>void}){return <label>{label}<select value={value} onChange={(e:{target:HTMLSelectElement})=>change(e.target.value)}>{options.map(([k,t])=><option value={k} key={k}>{t}</option>)}</select></label>}
createRoot(document.getElementById("root")!).render(<App/>);
